#!/bin/bash
# Pack everything a value-mining box needs and push it to S3.
#
#   bash corrections/cloud/pack_mining_code.sh
#     -> s3://pokebot-valuenet-389825051723/mining/code.tar.gz
#
# The tarball extracts to ONE directory on the box (/opt/pfb) whose layout is
# identical to the local repo, because corrections/mine_value.py derives
# everything from its own file location:
#     ROOT       = <tar root>
#     PY         = ROOT/foul-play/.venv/bin/python
#     LEAF_PROF  = ROOT/poke-engine/target/release/leaf_prof
#     AUDIT/LABEL= ROOT/valuenet/nets_v8b/v8b_{h2,s1}.bin
# so nothing in mine_value.py has to be patched for linux. The CORPUS constant
# is the one hardcoded /Users path left, and it is dead: --teams-source defaults
# to "ps" (teams are generated by fp.search.ps_teams, not read from disk).
#
# Contents (relative paths, extracted at /opt/pfb):
#   foul-play/      whole working tree minus .venv/.git/logs. Includes
#                   data/pokedex.json + data/moves.json + data/pkmn_sets_cache
#                   (fp.battle) and data/ps/gen9randombattle_sets.json -- the
#                   VENDORED sets.json that fp.search._ps_team_loop falls back
#                   to when the pokemon-showdown checkout is absent, which it is
#                   on the box. Byte-equal to the checkout as of 2026-08-15.
#   poke-engine/    source minus target/ (rebuilt on the box: wheel + leaf_prof)
#                   and minus tests/ (54 MB of parity fixtures, not needed to build).
#   valuenet/sprt/  run_duels.py -- mine_value.py imports opening_state from it.
#   valuenet/nets_v8b/v8b_{s1,h2}.{bin,constants.json}
#                   BOTH halves of each net. A missing .constants.json does NOT
#                   fail on the box: the engine silently falls back to defaults
#                   and the whole round measures a different net.
#   corrections/mine_value.py
#
# tar, not `git archive`: foul-play / poke-engine / valuenet are three separate
# nested repos (gitignored by the root repo), so one archive cannot span them,
# and shipping the working tree is what makes a cloud round reproduce the local
# one exactly.
set -euo pipefail
ROOT="${FP_ROOT:-/Users/sallyliu/pokemon-fast-bot}"
AWS="/Users/sallyliu/.awscli-venv/bin/aws"
[ -x "$AWS" ] || AWS="$(command -v aws)"
BUCKET="${S3_BUCKET:-pokebot-valuenet-389825051723}"
S3_PREFIX="${S3_PREFIX:-mining}"
TAR="${TAR:-$(mktemp -d)/code.tar.gz}"

NETS="valuenet/nets_v8b/v8b_s1.bin valuenet/nets_v8b/v8b_s1.constants.json
      valuenet/nets_v8b/v8b_h2.bin valuenet/nets_v8b/v8b_h2.constants.json"

cd "$ROOT"
# Refuse to ship an incomplete payload: every one of these is a 25-minute
# build's worth of wasted box time if it is discovered on the far side.
for f in $NETS \
         corrections/mine_value.py \
         valuenet/sprt/run_duels.py \
         foul-play/requirements.txt \
         foul-play/fp/search/ps_teams.py \
         foul-play/data/pokedex.json \
         foul-play/data/moves.json \
         foul-play/data/ps/gen9randombattle_sets.json \
         poke-engine/Cargo.toml \
         poke-engine/src/bin/leaf_prof.rs; do
  [ -s "$ROOT/$f" ] || { echo "pack_mining_code: missing $f" >&2; exit 1; }
done

# COPYFILE_DISABLE + --no-mac-metadata are load-bearing: every file here carries
# a com.apple.provenance xattr, and bsdtar encodes xattrs as AppleDouble `._name`
# members that GNU tar on the box extracts as literal junk files.
# `.claude` and `*/target` are not tidiness: poke-engine/.claude/worktrees holds
# a stale worktree with its own debug target dir, 1.25 GB of .rlib and
# incremental caches, which is 98% of an unfiltered tarball.
COPYFILE_DISABLE=1 tar czf "$TAR" --no-mac-metadata \
  --exclude='._*' --exclude='.git' --exclude='.venv' --exclude='node_modules' \
  --exclude='__pycache__' --exclude='.pytest_cache' --exclude='.DS_Store' \
  --exclude='.claude' --exclude='*/target' \
  --exclude='foul-play/logs' --exclude='foul-play/.env' \
  --exclude='poke-engine/tests' \
  foul-play poke-engine valuenet/sprt corrections/mine_value.py $NETS

# Fail loud. macOS `tar -t` silently re-merges AppleDouble members back into
# xattrs and reports a clean listing, so bsdtar cannot audit its own output.
python3 - "$TAR" <<'PYEOF'
import sys, tarfile
need = {
    "corrections/mine_value.py",
    "valuenet/sprt/run_duels.py",
    "valuenet/nets_v8b/v8b_s1.bin", "valuenet/nets_v8b/v8b_s1.constants.json",
    "valuenet/nets_v8b/v8b_h2.bin", "valuenet/nets_v8b/v8b_h2.constants.json",
    "foul-play/fp/search/ps_teams.py",
    "foul-play/data/ps/gen9randombattle_sets.json",
    "foul-play/data/pokedex.json", "foul-play/data/moves.json",
    "foul-play/requirements.txt",
    "poke-engine/src/bin/leaf_prof.rs", "poke-engine/Cargo.toml",
    "poke-engine/poke-engine-py/Cargo.toml",
}
names = tarfile.open(sys.argv[1]).getnames()
bad = [n for n in names if "/._" in n or n.startswith("._")]
if bad:
    sys.exit("pack_mining_code: %d AppleDouble members, e.g. %s" % (len(bad), bad[:3]))
missing = need - set(names)
if missing:
    sys.exit("pack_mining_code: tarball missing %s" % sorted(missing))
print("tarball ok: %d members, no AppleDouble, all required files present" % len(names))
PYEOF

ls -lh "$TAR"
$AWS s3 cp --only-show-errors "$TAR" "s3://$BUCKET/$S3_PREFIX/code.tar.gz"
echo "s3://$BUCKET/$S3_PREFIX/code.tar.gz"
