"""Generate evallab/enc2_prof.py -- a byte-for-byte copy of enc2.py with timing
checkpoints inserted into `encode_columnar` at block boundaries.

The copy is generated, never hand-edited, so it cannot drift from enc2.py.
Checkpoints are inserted BEFORE the anchor line; the label names the block that
just FINISHED. Anchors are unique substrings, asserted unique.
"""
import os
import sys

LAB = os.path.dirname(os.path.abspath(__file__))

# (anchor substring, label of the block that ENDS here)
ANCHORS = [
    ("    order = LL._slot_order(", "__START__"),
    ("    m = LL._gather(mi, order).astype(np.float32)", "1_static_reorder"),
    ("    boost12 = np.zeros((n, 12, 7), np.float32)", "2_gather_parse"),
    ("    # ================= effective speed", "3_spread_boosts"),
    ("    # ================= dynamic damage", "4_speed"),
    ("    numm_now = numerator(st_a)", "5_dmg_gather+mults"),
    ("    hpf12 = np.maximum(hp_frac, 1e-6)", "6_dmg_combine_now"),
    ("    # ================= assemble", "7_ko_matrix_calc"),
    ("    # ---- §2 per-side", "8_ids+per_mon"),
    ("    # ---- §3 relational", "9_per_side"),
    ("    # ---- §4 counterfactual", "10_relational"),
    ("    for lv in SETUP_LEVELS:", "11_cf_prep"),
    ("    feats[:, L.O_CFM:L.O_CFM + 12 * L.NCM]", "12_cf_setup_lv1"),
    ("    # ---- §5 global", "13_cf_side+tera"),
    ("    if debug is not None:", "14_global"),
]

HEADER = '''
# ---- profiling instrumentation (generated by make_prof.py) ----------------
import time as _time
import collections as _collections
PROF = _collections.OrderedDict()
_LAST = [0.0]


def _TK(label):
    t = _time.perf_counter()
    if label != "__START__":
        PROF[label] = PROF.get(label, 0.0) + (t - _LAST[0])
    _LAST[0] = t


def prof_reset():
    PROF.clear()
# ---------------------------------------------------------------------------
'''


def main():
    src = open(os.path.join(LAB, "enc2.py")).read()
    lines = src.split("\n")
    out = []
    inserted = []
    for ln in lines:
        for anchor, label in ANCHORS:
            if ln.startswith(anchor):
                assert label not in inserted, "anchor matched twice: " + label
                indent = " " * (len(ln) - len(ln.lstrip()))
                out.append('%s_TK(%r)' % (indent, label))
                inserted.append(label)
                break
        out.append(ln)
    missing = [l for _, l in ANCHORS if l not in inserted]
    assert not missing, "anchors not found: %s" % missing
    body = "\n".join(out)
    # put the instrumentation right after the imports block
    marker = "\nimport llencoder as LL"
    assert body.count(marker) == 1, body.count(marker)
    body = body.replace(marker, marker + "\n" + HEADER, 1)
    open(os.path.join(LAB, "enc2_prof.py"), "w").write(body)
    print("wrote enc2_prof.py with %d checkpoints" % len(inserted))

    # a second copy whose numpy is the counting proxy (see npcount.py)
    assert body.count("\nimport numpy as np\n") == 1
    cnt = body.replace("\nimport numpy as np\n", "\nimport npcount as np\n", 1)
    cnt = cnt.replace("import enc2_prof", "import enc2_count")
    open(os.path.join(LAB, "enc2_count.py"), "w").write(cnt)
    print("wrote enc2_count.py (numpy -> npcount proxy)")


if __name__ == "__main__":
    main()
